---
- name: Update packages
  apt:
    autoclean: yes
    update_cache: yes
    upgrade: yes
    force_apt_get: true

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    force_apt_get: true

- name: Configure journalctl logging
  lineinfile:
    path: /etc/systemd/journald.conf
    line: Storage=persistent
    insertafter: [Storage]
    state: present

- name: Restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: True

- name: Install unarchive utils
  apt:
    name: "{{ unarchive_packages }}"
